Spinner on login
Nutriway/nutriway-nextjs pull request #15
Opened 2023-06-03 14:18 UTC by tommasini

2023-06-03 14:39 UTC, Andree37 requested changes

2023-06-03 14:39 UTC, Andree37 commented on src/components/Forms/LoginForm.tsx
> +import Spinner from '../Skeletons/Spinner';
use @ instead of ../

2023-06-12 21:56 UTC, Andree37 commented
updates on this? @tommasini

2023-06-13 17:53 UTC, Andree37 approved these changes

2023-06-13 21:02 UTC, tiagoneto7 approved these changes

2023-06-13 21:02 UTC, merged